version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: smart_city_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Barasat@100
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - smart-city-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: smart_city_db
      DB_USER: postgres
      DB_PASSWORD: Barasat@100
    depends_on:
      postgres:
        condition: service_healthy
      python-api:
        condition: service_started
    networks:
    - smart-city-network

  python-api:
    build: ./ml_service
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "5500:5500"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  smart-city-network:
    driver: bridge

volumes:
  postgres_data:
